#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

/**
* Create an MCP server with core capabilities
*/
class MyFirstMCPServer {
  private server: Server;

  constructor() {
    this.server = new Server(
      {
        name: "my-first-mcp-server",
        version: "1.0.0",
      },
      {
        capabilities: {
          tools: {},
        },
      }
    );

    this.setupHandlers();
    this.setupErrorHandling();
  }

  /**
  * Set up request handlers
  */
  private setupHandlers(): void {
    // Handler for listing available tools
    this.server.setRequestHandler(
      ListToolsRequestSchema,
      async () => ({
        tools: [
          {
            name: "get_weather",
            description: "Get current weather information for a city using AI",
            inputSchema: {
              type: "object",
              properties: {
                city: {
                  type: "string",
                  description: "City name (e.g., 'London', 'New York')"
                },
                units: {
                  type: "string",
                  description: "Temperature units",
                  enum: ["celsius", "fahrenheit"],
                  default: "celsius"
                }
              },
              required: ["city"]
            }
          },
          {
            name: "hello_world",
            description: "Returns a friendly greeting message",
            inputSchema: {
              type: "object",
              properties: {
                name: {
                  type: "string",
                  description: "The name to greet",
                },
              },
              required: ["name"],
            },
          },
        ],
      })
    );

    // Handler for calling tools
    this.server.setRequestHandler(
      CallToolRequestSchema,
      async (request) => {
        const { name, arguments: args } = request.params;

        if (name === "get_weather") {
          if (!args || typeof args !== 'object') {
            throw new Error("Invalid arguments: expected object");
          }
          const city = args.city;
          if (typeof city !== 'string' || !city || city.trim().length === 0) {
            throw new Error("City must be a non-empty string");
          }

          try {
            // Use Ollama to generate weather information
            const prompt = `Generate realistic current weather information for ${city}.
            Return ONLY a JSON object with this exact structure:
            {
              "name": "${city}",
              "sys": {"country": "XX"},
              "main": {"temp": 20.5, "feels_like": 22.1, "humidity": 65},
              "weather": [{"description": "clear sky"}],
              "wind": {"speed": 3.2}
            }

            Use realistic weather data appropriate for the location. Temperature should be in Celsius. Choose an appropriate 2-letter country code for the city. Make the weather description realistic for the location and season.`;

            // Call Ollama API
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), 30000); // 30 second timeout

            const response = await fetch('http://localhost:11434/api/generate', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                model: 'llama3.2:latest',
                prompt: prompt,
                stream: false
              }),
              signal: controller.signal
            });

            clearTimeout(timeoutId);

            if (!response.ok) {
              throw new Error(`Ollama API error: ${response.status} ${response.statusText}. Make sure Ollama is running with 'ollama serve'.`);
            }

            const ollamaResult = await response.json();
            let data = JSON.parse(ollamaResult.response);

            // Format response
            const tempUnit = units === "fahrenheit" ? "°F" : "°C";
            const weatherText = `
Weather in ${data.name}, ${data.sys.country}:
- Temperature: ${data.main.temp}${tempUnit}
- Feels like: ${data.main.feels_like}${tempUnit}
- Conditions: ${data.weather[0].description}
- Humidity: ${data.main.humidity}%
- Wind Speed: ${data.wind.speed} m/s

*Generated by Ollama AI*
`.trim();

            // Return MCP response
            return {
              content: [
                {
                  type: "text",
                  text: weatherText
                }
              ]
            };
          } catch (error) {
            // Handle errors by using fallback data
            console.warn('Ollama API failed, using fallback data:', error instanceof Error ? error.message : 'Unknown error');
            const fallbackData: Record<string, any> = {
              "london": {
                name: "London",
                sys: { country: "GB" },
                main: { temp: 15.2, feels_like: 14.8, humidity: 82 },
                weather: [{ description: "light rain" }],
                wind: { speed: 3.6 }
              },
              "new york": {
                name: "New York",
                sys: { country: "US" },
                main: { temp: 22.5, feels_like: 24.1, humidity: 65 },
                weather: [{ description: "clear sky" }],
                wind: { speed: 2.1 }
              },
              "tokyo": {
                name: "Tokyo",
                sys: { country: "JP" },
                main: { temp: 18.7, feels_like: 18.2, humidity: 78 },
                weather: [{ description: "few clouds" }],
                wind: { speed: 1.8 }
              },
              "paris": {
                name: "Paris",
                sys: { country: "FR" },
                main: { temp: 12.8, feels_like: 11.9, humidity: 71 },
                weather: [{ description: "overcast clouds" }],
                wind: { speed: 4.2 }
              },
              "sydney": {
                name: "Sydney",
                sys: { country: "AU" },
                main: { temp: 24.3, feels_like: 25.1, humidity: 73 },
                weather: [{ description: "sunny" }],
                wind: { speed: 2.8 }
              }
            };
            const key = city.split(',')[0].toLowerCase().trim();
            data = fallbackData[key] || fallbackData["london"];
          }
        }

        if (name === "hello_world") {
          const userName = args?.name as string;

          if (!userName) {
            throw new Error("Name parameter is required");
          }

          return {
            content: [
              {
                type: "text",
                text: `Hello, ${userName}! Welcome to your first MCP server! 🎉`,
              },
            ],
          };
        }

        throw new Error(`Unknown tool: ${name}`);
      }
    );
  }

  /**
  * Set up error handling
  */
  private setupErrorHandling(): void {
    this.server.onerror = (error) => {
      console.error("[MCP Error]", error);
    };

    process.on("SIGINT", async () => {
      await this.server.close();
      process.exit(0);
    });
  }

  /**
  * Start the server
  */
  async start(): Promise<void> {
    const transport = new StdioServerTransport();
    await this.server.connect(transport);

    console.error("My First MCP Server running on stdio");
  }
}

/**
* Main entry point
*/
async function main() {
  const server = new MyFirstMCPServer();
  await server.start();
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});